### PR TITLE
Add separate account holder field for mandates

### PR DESCRIPTION
**Pull request by blipp**
Pull request by @kadl and me.

Partly addresses #96 by adding a separate account holder to SEPA mandates. The field is optional. For SEPA XML generation, the account holder is used as display name if it is not empty. If it is empty, the contact's is used as before.

Added test case for mandate creation with non-empty account holder. We did not run the tests because we do not have a working test environment set up (and you mention in the repository that you use a homegrown internal test system).

Manually tested:
- creating a mandate with (and without account holder) via the web UI
- display a mandate with (and without account holder) via the web UI
- update/replace a mandate with (and without account holder) via the web UI
- creating a mandate with (and without account holder) via create and createfull APIs
- generate SEPA XML with (and without account holder) via web UI

Edited to add:
- We did not adapt the “known bank account” feature to fill out account holders of previously used bank accounts. The reason is that CiviBanking currently does not have an account holder field for bank accounts. Possibly related issue for this: #566.
- We did not add a test case for SEPA XML generation because there are no tests for this yet, in general.

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks @blipp  and @kadl, that's pretty cool! 

I'll have a closer look and get back to you with some feedback, before merging this into ``master``. We also might have to rebase when other ongoing developments (like #572) are completed.

**Comment by bjendres** [comment]
Hi @kandl and @blipp. Thanks for the PR, that looks pretty good... 

However, in light of the fact that we have to release ``1.6`` asap because of #616, I'll push this to version ``1.7`` - it seems clean to me, but I'd like to risk of compatibility issues as small as possible. Plus, there's already some stuff in there that has the potential for this.

I suggest to create a ``1.7-alpha`` with this PR for you as soon as ``1.6`` is released, ok? Feel free to ping be again, should I forget :)

**Comment by bjendres** [comment]
I have now (after some unrelated issues with ``1.6``) merged it to ``master``, please let me know if this works for you.

I have two additional questions, though:
1. Could you provide some unit tests?
2. Can you think of a reasonable upgrade path, e.g. filling the account holder with the contact's display name?

**Comment by jensschuppe** [comment]
@bjendres Should this be further worked on in this merged PR or in a follow-up? Since this got merged, I'd advocate for setting it to `status:fixed`.

**Comment by jensschuppe** [comment]
@bjendres  Also, there are three related branches: `issue/581`, `issue/581_1.7`, and `issue/581_raw` that all got merged eventually - can we delete them?

**Pull request merged**
