### PR TITLE
Find existing contributions when the payment instrument of the mandate differs

### PR DESCRIPTION
**Pull request by jaapjansma**
**Description**

I have a use case where we use CiviSepa for Vipps Recurring (a norwegian payment system). 
We have created mandates with the payment instrument Vipps Recur instead of Sepa DD Recurring Transaction.
This is causing two kind of troubles:
* Contributions are created multiple times because the existing contribution could not be found because those are not paid with Vipps Recur 
* Or they are removed from existing groups. 

**Previous**

The Sepa code was looking for existing contribution for a mandate based on the payment instrument Sepa DD Recurring Transaction

**After**

* Looking up existing contributions is done based on the payment instrument of the mandate.
* I also have added a possibility to set a different payment instrument in the `CiviSepaMandate.Createfull` api
* And the contributions created by Sepa will get the payment instrument from the mandate

**Comment**
When the status is FRST we stil use the `Sepa DD First Transaction` as a payment instrument.

### CODE REVIEW

**Comment by bjendres** [comment]
Thanks. This issue should be covered by #572, I'll see if it makes sense to still include this particular PR.

**Comment by jensschuppe** [comment]
@jaapjansma Is this still relevant with #572 (PSP support) being released with `1.6`?

**Comment by bjendres** [comment]
@jaapjansma is this still relevant?

**Comment by jaapjansma** [comment]
I do think so. But it is too long ago to decide on this. So feel free to close this PR or merge it.

**Comment by bjendres** [comment]
> I do think so. But it is too long ago to decide on this. So feel free to close this PR or merge it.

Thanks. I think I'll close it for the time being. If somebody needs it after all, they would have to invest some time to bring it up to code.

**Pull request closed without merging**
