### PR TITLE
Fix for #697: Compatibility with CiviCRM 5.69

### PR DESCRIPTION
**Pull request by jaapjansma**
This fixes the issue with CiviCRM 5.69.

This PR is tested on CiviCRM 5.69 and 5.14 (so it is still backwards compatible)l

See #697

### CODE REVIEW

**Comment by jaapjansma** [comment]
@bjendres are you able to review this PR and merge it if ok?

**Comment by jensschuppe** [comment]
I think this should do a complete `civix upgrade`@`23.02.1` which leaves `_sepa_civix_civicrm_config()` with no template-specific code altogether …

**Comment by jaapjansma** [comment]
Yes that might be good. However I have a little objection against that it might break the working of this extension on older versions of CiviCRM when we do that.

**Comment by bjendres** [comment]
> @bjendres are you able to review this PR and merge it if ok?

I can't really assess the consequences of these changes, but it looks reasonable for me. If the two of you think it makes sense, I'll merge and release with ``1.10``.

**Comment by bjendres** [comment]
Thanks @jaapjansma

**Pull request merged**
