### PR TITLE
Foreign keys definition #301

### PR DESCRIPTION
**Pull request by scardinius**
Due to #301 issue:

* Added foreign key to column civicrm_sdd_contribution_txgroup.contribution_id
* Added foreign key to column civicrm_sdd_sdd_creditor.payment_processor_id
* The SQL code was reformatted into consistent formatting

### CODE REVIEW

**Comment by systopia** [comment]
Hi @scardinius. I finally found the time to look into your pull requests. Could you tell me: Did you simply format the file, or modify the SQL as well? https://github.com/Project60/org.project60.sepa/pull/320/files is not very helpful here...

**Comment by scardinius** [comment]
Hi @systopia. 

I formated the file and added those lines:
* civicrm_sdd_contribution_txgroup.contribution_id, added foreign key https://github.com/Project60/org.project60.sepa/pull/320/files#diff-fa7e7efca5c23811238ae1a4a28bde03R125
* civicrm_sdd_sdd_creditor.payment_processor_id, modified definition https://github.com/Project60/org.project60.sepa/pull/320/files#diff-fa7e7efca5c23811238ae1a4a28bde03R16 
* civicrm_sdd_sdd_creditor.payment_processor_id, added foreign key https://github.com/Project60/org.project60.sepa/pull/320/files#diff-fa7e7efca5c23811238ae1a4a28bde03R27

**Comment by systopia** [comment]
Hi @scardinius: Thanks, that helped a lot :)

Why exactly did you want to add ``payment_processor_id`` to the creditor? We had a discussion about this (quite some time ago), and we decided it's better to connect it the other way around (like it is now): connect the payment processor to one creditor - otherwise you would have to have a new creditor for each pp. But if you can make a good case for your approach...

**Comment by scardinius** [comment]
I only added foreign key. This column `payment_processor_id` existed before I started working on extension :-)

**Comment by systopia** [comment]
Ah, ok :)
@tttp Could we remove the ``payment_processor_id`` altogether, then? I'm definitely not using it, and neither is anyone else by the looks of it. Maybe Olaf? See also https://github.com/Project60/org.project60.sepa/issues/325

**Comment by tttp** [comment]
ooh, autumn cleaning style then

yeap, looks like a rest from pre 1.0 days. @scardinius can you remove the pp id?

**Comment by scardinius** [comment]
@tttp yes, I can.

**Comment by scardinius** [comment]
This PR is too messed up so I closed it and I will prepare new one in the future.

**Pull request closed without merging**
