### PR TITLE
Fixed bug in the new token evaluation

### PR DESCRIPTION
**Pull request by kainuk**
The tokens still did not work in the new token system. (I missed this in the last test because on my system the old token replacement was also active and hid the bug).

Two fixes.
- One misnomed variable.
- Tokes replacement work better with an empty string.

### CODE REVIEW

**Comment by bjendres** [comment]
Looks good to me, thank you @kainuk

@jensschuppe any objections/concerns?

**Review by jensschuppe — APPROVED** [review]

**Comment by kainuk** [comment]
Hi @bjendres or @jensschuppe, can this be merged. I have a customer needs this PR, but is in favour of installing the official source.

**Comment by bjendres** [comment]
> Hi @bjendres or @jensschuppe, can this be merged. I have a customer needs this PR, but is in favour of installing the official source.

I have merged it and will tag an alpha version.

Just for the future: this would've been easier to review if you hadn't renamed ``$row`` to ``$tokenRow`` for some reason...

**Comment by bjendres** [comment]
Here you go, @kainuk: https://github.com/Project60/org.project60.sepa/releases/tag/1.10-alpha4

**Comment by kainuk** [comment]
Thanks @bjendres

**Pull request merged**
