### PR TITLE
Fix undefined countryLimit() in CiviCRM 4.7 #351

### PR DESCRIPTION
**Pull request by scardinius**
Method `CRM_Core_Config::countryLimit()` was moved to `CRM_Core_BAO_Country::countryLimit()` in version 4.7. This fix checks If we are working on 4.7 or other version and use proper code.

Explanation:
https://github.com/civicrm/civicrm-core/commit/0acb7f15552889bdba24b013da4dafebebf3a838
https://github.com/civicrm/civicrm-core/commit/90777b73c3a04e023c36417abf3b4ab7a282dfb9

### CODE REVIEW

**Comment by systopia** [comment]
Great, thanks! Could you please use ``version_compare()`` though? See e.g. https://github.com/Project60/org.project60.sepa/blob/1.2.2.beta1/CRM/Utils/SepaCustomisationHooks.php#L44  ...although your approach is pretty ingenious :)

**Comment by scardinius** [comment]
You're right, code with `version_compare()` looks better :-)

**Comment by systopia** [comment]
> You're right, code with ``version_compare()`` looks better :-)

It does, doesn't it? :-)

**Comment by Fabian-SYSTOPIA** [comment]
I can confirm that the fix is working for (CiviCRM 4.7.12)

**Pull request merged**
