### PR TITLE
Fix compatibility with CiviCRM 4.7.20

### PR DESCRIPTION
**Pull request by DanielvV**
Installation is broken due to changes in CiviCRM's CRM_Utils_File::sourceSQLFile

### CODE REVIEW

**Comment by systopia** [comment]
@DanielvV: Great, thank you. Could you confirm that this is compatible with 4.6 as well?

**Comment by DanielvV** [comment]
No, I think it is (should be, by reading the code).

**Comment by DanielvV** [comment]
Will try to test this now.

**Comment by DanielvV** [comment]
PHP 5.6
### +
CiviCRM 4.6.28
### +
`drush cvapi extension.download key=org.project60.sepa url=https://github.com/DanielvV/org.project60.sepa/archive/1.2.5.alpha2.zip`
### =
afbeelding

**Comment by DanielvV** [comment]
It is compatible with CiviCRM 4.6.28

**Comment by systopia** [comment]
Brilliant, thank you @DanielvV, I will release a new alpha2 soon

**Pull request merged**
