### PR TITLE
Adding language ressources

### PR DESCRIPTION
**Pull request by eptbertram**
Adding language ressources from Transifex for es_ES, fr_FR, nl_NL, pl_PL. 
See: https://github.com/Project60/org.project60.sepa/issues/519

### CODE REVIEW

**Comment by eptbertram** [comment]
hm, copy & paste not that easy... Sorry Björn

**Comment by bjendres** [comment]
Thanks @eptbertram

**Comment by eptbertram** [comment]
Dear @bjendres are the failed tests harming the extension? I don't know what they are meaning - something about duplicate status strings.

**Comment by bjendres** [comment]
> are the failed tests harming the extension

No, they shouldn't in this case. But I'll keep an eye on them...

**Pull request merged**
